import mapty from "../../assets/mapty.png";
import simon from "../../assets/simon.png"
import jibber from "../../assets/jibberjobber.png"
import task from "../../assets/task.png"
import ecommerce from "../../assets/E-commerce.png"

const data = [
  {
    id: 1,
    category: 'frontend',
    image: ecommerce ,
    title: 'e-commerce website',
    desc: " Created a e-commerce platform with essential features like product listings, cart, and secure payment options.",
    tech: "ReactJS , MongoDB , Express.js, Node.js , Redux Toolkit , Passport JS , REST API , Nodemailer , Stripe ",
    demo: 'https://vercel-ecommerce-qxye81g1k-divyansh-singhs-projects.vercel.app/',
    github: 'https://github.com/divyansh2209/e-commerce-frontend'
  },
  {
    id: 2,
    category: 'frontend',
    image: task,
    title: 'Task manager',
    desc: "  Developed Task Manager web application with frontend on ReactJS and backend on NodeJS , ExpressJs and MongoDB database .  Enabling efficient task management with add, edit, and delete functionalities ",
    tech: "ReactJS , MongoDB , Express.js, Node.js , REST API",
    demo: 'https://github.com/divyansh2209/Task-Manager',
  },
  {
    id: 3,
    category: "frontend",
    image: mapty,
    title: "Mapty-Personal workout tracker",
    desc: "It is a webapp which helps to track personal workouts with a focus on simplicity and clean design. Utilized a third party library called leaflet",
    tech: "HTML , CSS , Javascript , API",
    demo: "https://divyansh2209.github.io/Mapty-personal_workout_tracker/",
    github: "https://github.com/divyansh2209/Mapty-personal_workout_tracker",
  },
  {
    id: 4,
    category: 'frontend',
    image: simon,
    title: 'Simon game',
    desc: " The Simon game is a memory-based game where the player must repeat a sequence of colors and sounds that are generated by the game. ",
    tech: "HTML , CSS , Javascript",
    demo: 'https://divyansh2209.github.io/Simon-game/',
    github: 'https://github.com/divyansh2209/Simon-game'
  },
];

export default data;
